# permissions for end users to view helloapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helloapp-viewer-role
rules:
- apiGroups:
  - apps.hello.com
  resources:
  - helloapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.hello.com
  resources:
  - helloapps/status
  verbs:
  - get
